class ErrorCode:
    # Auth
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_ALREADY_EXISTS = "ACCOUNT_ALREADY_EXISTS"
    ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
    
    SIGNUP_SESSION_EXPIRED = "SIGNUP_SESSION_EXPIRED"

    OTP_EXPIRED = "OTP_EXPIRED"
    OTP_INVALID = "OTP_INVALID"

    REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID"
    PASSWORD_RESET_TOKEN_INVALID = "PASSWORD_RESET_TOKEN_INVALID"
    PASSWORD_RESET_TOKEN_MISSING = "PASSWORD_RESET_TOKEN_MISSING"
    SAME_AS_PREVIOUS_PASSWORD = "SAME_AS_PREVIOUS_PASSWORD"

    #invitation
    INVALID_INVITATION = "INVALID_INVITATION"

    #workspace
    WORKSPACE_MEMBER_NOT_FOUND = "WORKSPACE_MEMBER_NOT_FOUND"

    #goals
    GOAL_NOT_FOUND = "GOAL_NOT_FOUND"


    # Validation
    VALIDATION_ERROR = "VALIDATION_ERROR"

    # General
    PERMISSION_DENIED = "PERMISSION_DENIED"
    NOT_FOUND = "NOT_FOUND"
    SERVER_ERROR = "SERVER_ERROR"
    RATE_LIMITED = "RATE_LIMITED" 
