class ErrorCode:
    # Auth
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_ALREADY_EXISTS = "ACCOUNT_ALREADY_EXISTS"
    ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
    OTP_EXPIRED = "OTP_EXPIRED"
    SIGNUP_SESSION_EXPIRED = "SIGNUP_SESSION_EXPIRED"
    OTP_INVALID = "OTP_INVALID"

    # Validation
    VALIDATION_ERROR = "VALIDATION_ERROR"

    # General
    PERMISSION_DENIED = "PERMISSION_DENIED"
    NOT_FOUND = "NOT_FOUND"
    SERVER_ERROR = "SERVER_ERROR"
    RATE_LIMITED = "RATE_LIMITED" 
    TOKEN_ERROR = "TOKEN_ERROR"
    TOKEN_MISSING = "TOKEN_MISSING"
    INVALID_OR_EXPIRED_TOKEN = "INVALID_OR_EXPIRED_TOKEN"