services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: teeming_db
      POSTGRES_USER: teeming_user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  celery_worker:
    build: ./backend
    entrypoint: []
    command: celery -A config worker -l info
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
      - backend

volumes:
  pgdata: