services:
  db:
    ports:
      - "5433:5432"

  redis:
    ports:
      - "6380:6379"

  backend:
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app
          ignore:
            - "**/__pycache__/"
            - "**/*.pyc"
        - action: rebuild
          path: ./requirements.txt

  celery_worker:
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app
          ignore:
            - "**/__pycache__/"
            - "**/*.pyc"
        - action: rebuild
          path: ./requirements.txt

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend