services:
  db:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  backend:
    restart: unless-stopped

  celery_worker:
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped