# Generated by Django 6.0.5 on 2026-05-19 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_verified'),
        ('workspace', '0002_workspacemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_active_users', to='workspace.workspace'),
        ),
    ]
