# Generated by Django 6.0.5 on 2026-07-08 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInMetricValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'checkin_metric_values',
            },
        ),
        migrations.CreateModel(
            name='OutcomeCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('measuring', 'Still Measuring'), ('promising', 'Looking Promising'), ('achieved', 'Goal Achieved'), ('not_working', 'Not Working')], default='measuring', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outcome_checkins',
            },
        ),
        migrations.CreateModel(
            name='OutcomeMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('baseline_value', models.FloatField(blank=True, null=True)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('percentage', 'Percentage'), ('number', 'Number'), ('currency', 'Currency'), ('hours', 'Hours'), ('days', 'Days'), ('minutes', 'Minutes'), ('score', 'Score')], default='number', max_length=20)),
                ('direction', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], default='increase', max_length=20)),
            ],
            options={
                'db_table': 'outcome_metrics',
            },
        ),
    ]
