# Generated by Django 6.0.5 on 2026-06-07 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goal', '0003_starredgoal'),
        ('workspace', '0007_workspace_deleted_at_workspace_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('measuring', 'Still Measuring'), ('promising', 'Looking Promising'), ('achieved', 'Goal Achieved'), ('not_working', 'Not Working')], default='measuring', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_checkins', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_checkins', to='goal.goal')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspace.workspace')),
            ],
            options={
                'db_table': 'outcome_checkins',
            },
        ),
        migrations.CreateModel(
            name='OutcomeMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('baseline_value', models.FloatField(blank=True, null=True)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('percentage', 'Percentage'), ('number', 'Number'), ('currency', 'Currency'), ('hours', 'Hours'), ('days', 'Days'), ('score', 'Score')], default='number', max_length=20)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_metrics', to='goal.goal')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspace.workspace')),
            ],
            options={
                'db_table': 'outcome_metrics',
            },
        ),
        migrations.CreateModel(
            name='CheckInMetricValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspace.workspace')),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='outcome.outcomecheckin')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_values', to='outcome.outcomemetric')),
            ],
            options={
                'db_table': 'checkin_metric_values',
                'unique_together': {('checkin', 'metric')},
            },
        ),
    ]
