# Generated by Django 6.0.5 on 2026-07-08 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goal', '0002_initial'),
        ('outcome', '0001_initial'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinmetricvalue',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name='outcomecheckin',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outcomecheckin',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_checkins', to='goal.goal'),
        ),
        migrations.AddField(
            model_name='outcomecheckin',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name='checkinmetricvalue',
            name='checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='outcome.outcomecheckin'),
        ),
        migrations.AddField(
            model_name='outcomemetric',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outcomemetric',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_metrics', to='goal.goal'),
        ),
        migrations.AddField(
            model_name='outcomemetric',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name='checkinmetricvalue',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_values', to='outcome.outcomemetric'),
        ),
        migrations.AlterUniqueTogether(
            name='checkinmetricvalue',
            unique_together={('checkin', 'metric')},
        ),
    ]
