# Generated by Django 6.0.5 on 2026-06-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcome', '0002_outcomemetric_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomemetric',
            name='direction',
            field=models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], default='increase', max_length=20),
        ),
    ]
