# Generated by Django 6.0.5 on 2026-08-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_initial'),
        ('outcome', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomecheckin',
            name='contributed_ideas',
            field=models.ManyToManyField(blank=True, related_name='outcome_checkins', to='idea.idea'),
        ),
    ]
