# Generated by Django 6.0.5 on 2026-06-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcome', '0003_outcomemetric_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcomemetric',
            name='unit',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('number', 'Number'), ('currency', 'Currency'), ('hours', 'Hours'), ('days', 'Days'), ('minutes', 'Minutes'), ('score', 'Score')], default='number', max_length=20),
        ),
    ]
