# Generated by Django 6.0.5 on 2026-07-08 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistantResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('summary', 'Summary'), ('blockers', 'Blockers'), ('idea_suggestions', 'Idea Suggestions'), ('custom_chat', 'Custom Chat')], max_length=30)),
                ('request_text', models.TextField(blank=True, null=True)),
                ('content', models.JSONField()),
                ('is_shared', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ai_assistant_responses',
            },
        ),
    ]
