# Generated by Django 6.0.5 on 2026-07-08 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistantresponse',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='goal.goal'),
        ),
    ]
