# Generated by Django 6.0.5 on 2026-06-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiinsight',
            name='title',
        ),
    ]
