# Generated by Django 6.0.5 on 2026-06-17 08:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_remove_aiinsight_title'),
        ('goal', '0003_starredgoal'),
        ('workspace', '0008_alter_workspacemember_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AIInsight',
            new_name='AIAssistantResponse',
        ),
        migrations.AlterModelTable(
            name='aiassistantresponse',
            table='ai_assistant_responses',
        ),
    ]
