# Generated by Django 6.0.5 on 2026-06-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_rename_aiinsight_aiassistantresponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiassistantresponse',
            name='type',
            field=models.CharField(choices=[('summary', 'Summary'), ('blockers', 'Blockers'), ('idea_suggestions', 'Idea Suggestions'), ('custom_chat', 'Custom Chat')], max_length=30),
        ),
    ]
