# Generated by Django 6.0.5 on 2026-06-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_alter_aiassistantresponse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistantresponse',
            name='request_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
