# Generated by Django 6.0.5 on 2026-05-20 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspacemember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
