# Generated by Django 6.0.5 on 2026-05-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_invitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
