# Generated by Django 6.0.5 on 2026-05-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_delete_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('owner', 'Owner')], default='member', max_length=15),
        ),
    ]
