# Generated by Django 6.0.5 on 2026-06-09 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_workspace_deleted_at_workspace_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemember',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspace.workspace'),
        ),
    ]
