# Generated by Django 6.0.5 on 2026-06-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_alter_workspacemember_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
