# Generated by Django 6.0.5 on 2026-06-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_workspace_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='logo',
            new_name='logo_url',
        ),
    ]
