# Generated by Django 6.0.5 on 2026-06-19 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_rename_logo_workspace_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='logo_url',
            new_name='logo_key',
        ),
    ]
