# Generated by Django 6.0.5 on 2026-06-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_rename_logo_url_workspace_logo_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='logo_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
