# Generated by Django 6.0.5 on 2026-07-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_alter_workspace_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workspace',
            old_name='logo_key',
            new_name='logo_full_key',
        ),
        migrations.AddField(
            model_name='workspace',
            name='logo_thumb_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
