# Generated by Django 6.0.5 on 2026-07-08 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscription.plan'),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='scheduled_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_subscriptions', to='subscription.plan'),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='subscription.workspacesubscription'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='unique_plan_code_version'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('code',), name='unique_active_plan_code'),
        ),
        migrations.AddIndex(
            model_name='workspacesubscription',
            index=models.Index(fields=['workspace', 'status'], name='workspace_s_workspa_a0a04d_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacesubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('workspace',), name='one_active_subscription_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontransaction',
            index=models.Index(fields=['workspace'], name='subscriptio_workspa_d0ba47_idx'),
        ),
    ]
