# Generated by Django 6.0.5 on 2026-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_plan_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee (₹)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('SGD', 'Singapore Dollar (S$)'), ('JPY', 'Japanese Yen (¥)')], default='INR', max_length=3),
        ),
    ]
