# Generated by Django 6.0.5 on 2026-07-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_seed_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='can_export_workspace_data',
        ),
    ]
