# Generated by Django 6.0.5 on 2026-06-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_plan_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacesubscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
