# Generated by Django 6.0.5 on 2026-06-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_workspacesubscription_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacesubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workspacesubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
