# Generated by Django 6.0.5 on 2026-06-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_workspacesubscription_stripe_customer_id_and_more'),
        ('workspace', '0008_alter_workspacemember_workspace'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workspacesubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('workspace',), name='one_active_subscription_per_workspace'),
        ),
    ]
