# Generated by Django 6.0.5 on 2026-06-14 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_workspacesubscription_one_active_subscription_per_workspace'),
        ('workspace', '0008_alter_workspacemember_workspace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='plan',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workspacesubscription',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='workspace.workspace'),
        ),
    ]
