# Generated by Django 6.0.5 on 2026-06-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_alter_plan_options_plan_display_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='display_order',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
