# Generated by Django 6.0.5 on 2026-06-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_alter_plan_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['tier']},
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='display_order',
            new_name='tier',
        ),
    ]
