# Generated by Django 6.0.5 on 2026-06-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_alter_plan_options_rename_display_order_plan_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
