# Generated by Django 6.0.5 on 2026-06-23 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_workspacesubscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesubscription',
            name='scheduled_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_subscriptions', to='subscription.plan'),
        ),
    ]
