# Generated by Django 6.0.5 on 2026-06-28 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_workspacesubscription_scheduled_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['tier', 'version']},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_active',
        ),
        migrations.AddField(
            model_name='plan',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_versions', to='subscription.plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tier',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='unique_plan_code_version'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('code',), name='unique_active_plan_code'),
        ),
    ]
