# Generated by Django 6.0.5 on 2026-06-29 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_alter_plan_options_remove_plan_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacesubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscription.plan'),
        ),
    ]
