# Generated by Django 6.0.5 on 2026-06-29 06:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_alter_workspacesubscription_plan'),
        ('workspace', '0013_alter_workspace_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('renewal', 'Renewal'), ('upgrade', 'Upgrade'), ('downgrade', 'Downgrade')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('billing_period_start', models.DateTimeField()),
                ('billing_period_end', models.DateTimeField()),
                ('gateway_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_url', models.URLField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.plan')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='subscription.workspacesubscription')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='workspace.workspace')),
            ],
            options={
                'db_table': 'subscription_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace'], name='subscriptio_workspa_d0ba47_idx')],
            },
        ),
    ]
