# Generated by Django 6.0.5 on 2026-07-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_subscriptiontransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesubscription',
            name='stripe_schedule_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
