# Generated by Django 6.0.5 on 2026-07-01 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0017_alter_workspacesubscription_workspace'),
        ('workspace', '0013_alter_workspace_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacesubscription',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='workspace.workspace'),
        ),
    ]
