# Generated by Django 6.0.5 on 2026-07-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0018_alter_workspacesubscription_workspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='can_use_AI_ENHANCEMENTS',
            new_name='can_use_ai_enhancements',
        ),
    ]
