export const errorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  SIGNUP_SESSION_EXPIRED: 'SIGNUP_SESSION_EXPIRED',
  RATE_LIMITED: 'RATE_LIMITED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
}