export const errorCodes = {
    // Auth
    AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",

    // User
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
    USER_ACCOUNT_SUSPENDED: "USER_ACCOUNT_SUSPENDED",

    // Validation
    VALIDATION_ERROR: "VALIDATION_ERROR",
    MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",

    //Others
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
}

export const userFacingErrorCodes = [
    errorCodes.AUTH_INVALID_CREDENTIALS,
    errorCodes.USER_ACCOUNT_SUSPENDED,
    errorCodes.AUTH_TOKEN_EXPIRED,
]
