export const PERMISSIONS = {
  MANAGE_GOALS: 'manage_goals',
  INVITE_MEMBERS: 'invite_members',
  MANAGE_TEAM: 'manage_team',
  MANAGE_SETTINGS: 'manage_settings',
  DELETE_WORKSPACE: 'delete_workspace',
  VIEW_GOALS: 'view_goals',
  LEAVE_WORKSPACE: 'leave_workspace',
  UPGRADE_PLAN: 'upgrade_plan',
  MOVE_IDEA_PLANNED: 'move_idea_planned',
  MOVE_IDEA_PROGRESS: 'move_idea_progress',
  MOVE_IDEA_DONE: 'move_idea_done',
  DELETE_OTHERS_IDEA: 'delete_others_idea',
  DROP_IDEA: 'drop_idea',
  MANAGE_METRICS: 'manage_metrics',
  MANAGE_CHECKINS: 'manage_checkins',
}