import { PERMISSIONS } from "../constants/permissions"

const MEMBER_PERMISSION = [
  PERMISSIONS.LEAVE_WORKSPACE
]

const ADMIN_PERMISSION = [
  ...MEMBER_PERMISSION,
  PERMISSIONS.MANAGE_GOALS,
  PERMISSIONS.INVITE_MEMBERS,
  PERMISSIONS.MANAGE_TEAM,
  PERMISSIONS.MANAGE_SETTINGS,
  PERMISSIONS.MOVE_IDEA_PROGRESS,
  PERMISSIONS.MOVE_IDEA_DONE,
  PERMISSIONS.DELETE_OTHERS_IDEA,
  PERMISSIONS.DROP_IDEA,
  PERMISSIONS.MANAGE_CHECKINS,
  PERMISSIONS.MANAGE_METRICS,
]

const OWNER_PERMISSION = [
  ...ADMIN_PERMISSION.filter(
    permission => permission != PERMISSIONS.LEAVE_WORKSPACE
  ),
  PERMISSIONS.DELETE_WORKSPACE,
  PERMISSIONS.UPGRADE_PLAN
]


const ROLE_PERMISSIONS = {
  Owner: OWNER_PERMISSION,
  Admin: ADMIN_PERMISSION,
  Member: MEMBER_PERMISSION
}


export const can = (role, permission) =>
  ROLE_PERMISSIONS[role]?.includes(permission) ?? false