# Generated by Django 6.0.5 on 2026-07-08 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goal', '0002_initial'),
        ('idea', '0001_initial'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ideas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idea',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='goal.goal'),
        ),
        migrations.AddField(
            model_name='idea',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name='ideaassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idea_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ideaassignment',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_ideas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ideaassignment',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='idea.idea'),
        ),
        migrations.AddField(
            model_name='ideaassignment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name='idealike',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='idea.idea'),
        ),
        migrations.AddField(
            model_name='idealike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ideastatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='idea_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ideastatushistory',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='idea.idea'),
        ),
        migrations.AddField(
            model_name='ideastatushistory',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspace.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='ideaassignment',
            unique_together={('idea', 'assignee')},
        ),
        migrations.AddConstraint(
            model_name='idealike',
            constraint=models.UniqueConstraint(fields=('idea', 'user'), name='unique_idea_like'),
        ),
    ]
