# Generated by Django 6.0.5 on 2026-06-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='deadline',
            new_name='target_date',
        ),
    ]
