# Generated by Django 6.0.5 on 2026-06-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_rename_deadline_idea_target_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='target_date',
            new_name='deadline',
        ),
    ]
