# Generated by Django 6.0.5 on 2026-06-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_rename_target_date_idea_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('done', 'Done')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='ideastatushistory',
            name='from_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('done', 'Done')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ideastatushistory',
            name='to_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('done', 'Done')], max_length=20),
        ),
    ]
