# Generated by Django 6.0.5 on 2026-06-06 07:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_alter_idea_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ideaassignment',
            unique_together={('idea', 'assignee')},
        ),
        migrations.AlterModelTable(
            name='ideaassignment',
            table='idea_assignments',
        ),
    ]
