# Generated by Django 6.0.5 on 2026-07-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0007_idealike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idealike',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='idealike',
            name='is_deleted',
        ),
    ]
