# Generated by Django 6.0.5 on 2026-07-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0008_remove_idealike_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idealike',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='idealike',
            name='workspace',
        ),
    ]
