# Generated by Django 6.0.5 on 2026-08-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_tour',
            field=models.BooleanField(default=False),
        ),
    ]
