# Generated by Django 6.0.5 on 2026-05-27 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
