# Generated by Django 6.0.5 on 2026-06-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar_url',
            new_name='avatar_key',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
