# Generated by Django 6.0.5 on 2026-06-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_avatar_url_user_avatar_key_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_thumb_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
