# Generated by Django 6.0.5 on 2026-06-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_avatar_thumb_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_plan',
        ),
    ]
