# Generated by Django 6.0.5 on 2026-07-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_current_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar_thumb_key',
            new_name='avatar_full_key',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_thumb_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
